included:
  - Sources
  - Tests

excluded:
  - .build
  - Build
  - Frameworks
  - logs

opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - force_unwrapping
  - force_cast
  - force_try

line_length:
  warning: 140
  error: 180

identifier_name:
  min_length: 2
  max_length: 50

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 800
  error: 1000

function_body_length:
  warning: 120
  error: 160
